name: microbosh
releases:
  bosh:
    url: /home/jhkim/openpass/release/bosh-230.tgz
  bosh-aws-cpi:
    url: /home/jhkim/openpass/release/bosh-aws-cpi-release-36.tgz
resource_pools:
  vms:
    stemcell: 
      url: [stemcell]
    env:
      bosh:
        password: [microboshPw] 
    cloud_properties:
      instance_type: m3.large
      availability_zone: us-east-1a
networks:
  private:
    subnets:
    - range: [subnetRange]
      gateway: [gateway]
      dns:
      - [dns]
      cloud_properties: 
        subnet: [subnetId]
jobs:
  bosh:
    networks:
      private:
        static_ips: 
        - [directorPrivateIp]
      public:
        static_ips:
        - [directorPublicIp]
    properties:
      director: 
        name: my-bosh
      aws:
        access_key_id: [awsKey]
        secret_access_key: [secretAccessKey]
        default_key_name: bosh
        default_security_groups: 
        - [securGroupName]
        region: us-east-1
      ntp: 
      - 1.kr.pool.ntp.org
        0.asia.pool.ntp.org
        1.asia.pool.ntp.org
cloud_provider:
  ssh_tunnel:
    private_key: [privateKey]